In [90]:
import numpy as np

In [91]:
a=np.array([[1,2],[4,5]],dtype=np.int32)
b=np.array([[7,8],[9,10]],dtype=np.int32)
print('uint32 type operation:\t',a.astype(np.uint32)-b.astype(np.uint32),'\nint32 type operation:\t',a-b)

uint32 type operation:	 [[4294967290 4294967290]
 [4294967291 4294967291]] 
int32 type operation:	 [[-6 -6]
 [-5 -5]]


In [92]:
np.arange(2,10,1.2,dtype=float)

array([2. , 3.2, 4.4, 5.6, 6.8, 8. , 9.2])

In [93]:
np.linspace(2,10,7,dtype=float)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [94]:
np.eye(6,6,2,dtype=int)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [95]:
d=np.diag([11,21,31,41])
d

array([[11,  0,  0,  0],
       [ 0, 21,  0,  0],
       [ 0,  0, 31,  0],
       [ 0,  0,  0, 41]])

In [96]:
np.diag(d)

array([11, 21, 31, 41])

In [97]:
v=np.arange(2,10,3,dtype=int) 
v

array([2, 5, 8])

In [98]:
np.vander(v,4)

array([[  8,   4,   2,   1],
       [125,  25,   5,   1],
       [512,  64,   8,   1]])